<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>loginOrganization</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5b29087b-60ea-4412-8696-e9939055e608</testSuiteGuid>
   <testCaseLink>
      <guid>c5a71105-0abd-496a-94bf-dac1ff9c3220</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/loginOrganizationWithCorrectOrganizationName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84e3dee1-15e5-4297-8818-099ec4ace729</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7f89204-c765-43d8-9067-eaf880ad26fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/loginOrganizationWithEmptyOrganizationName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d412ba06-dedd-47bf-9701-eb4670d62179</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5a21c62-4fcf-4a6c-8c51-5e457849a722</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/loginOrganizationWithIncorrectOrganizationName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8192ff14-d967-433d-862b-91f47b9e7373</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab4f2e19-4172-4277-bdfc-566c61d20eae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/loginOrganizationWithCharacterAndNumberInOrganizationName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3ca2187-d859-4195-9556-a43bece90672</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
